/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RibbonRouteImport } from './routes/ribbon'
import { Route as MarketplacesRouteImport } from './routes/marketplaces'
import { Route as FitaDeCetimRouteImport } from './routes/fita-de-cetim'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as BrindesRouteImport } from './routes/brindes'
import { Route as BoppRouteImport } from './routes/bopp'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FitaDeCetimIndexRouteImport } from './routes/fita-de-cetim.index'
import { Route as BrindesIndexRouteImport } from './routes/brindes.index'
import { Route as FitaDeCetimImpressoraParaCetimRouteImport } from './routes/fita-de-cetim.impressora-para-cetim'
import { Route as EtiquetasPrecoRouteImport } from './routes/etiquetas.preco'
import { Route as BrindesAgendaPersonalizadaRouteImport } from './routes/brindes.agenda-personalizada'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated.admin.produtos'
import { Route as AuthenticatedAdminImportacaoRouteImport } from './routes/_authenticated.admin.importacao'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RibbonRoute = RibbonRouteImport.update({
  id: '/ribbon',
  path: '/ribbon',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacesRoute = MarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => rootRouteImport,
} as any)
const FitaDeCetimRoute = FitaDeCetimRouteImport.update({
  id: '/fita-de-cetim',
  path: '/fita-de-cetim',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const BrindesRoute = BrindesRouteImport.update({
  id: '/brindes',
  path: '/brindes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoppRoute = BoppRouteImport.update({
  id: '/bopp',
  path: '/bopp',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FitaDeCetimIndexRoute = FitaDeCetimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FitaDeCetimRoute,
} as any)
const BrindesIndexRoute = BrindesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrindesRoute,
} as any)
const FitaDeCetimImpressoraParaCetimRoute =
  FitaDeCetimImpressoraParaCetimRouteImport.update({
    id: '/impressora-para-cetim',
    path: '/impressora-para-cetim',
    getParentRoute: () => FitaDeCetimRoute,
  } as any)
const EtiquetasPrecoRoute = EtiquetasPrecoRouteImport.update({
  id: '/etiquetas/preco',
  path: '/etiquetas/preco',
  getParentRoute: () => rootRouteImport,
} as any)
const BrindesAgendaPersonalizadaRoute =
  BrindesAgendaPersonalizadaRouteImport.update({
    id: '/agenda-personalizada',
    path: '/agenda-personalizada',
    getParentRoute: () => BrindesRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportacaoRoute =
  AuthenticatedAdminImportacaoRouteImport.update({
    id: '/importacao',
    path: '/importacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/bopp': typeof BoppRoute
  '/brindes': typeof BrindesRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contato': typeof ContatoRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/ferramentas': typeof FerramentasRoute
  '/fita-de-cetim': typeof FitaDeCetimRouteWithChildren
  '/marketplaces': typeof MarketplacesRoute
  '/ribbon': typeof RibbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/brindes/agenda-personalizada': typeof BrindesAgendaPersonalizadaRoute
  '/etiquetas/preco': typeof EtiquetasPrecoRoute
  '/fita-de-cetim/impressora-para-cetim': typeof FitaDeCetimImpressoraParaCetimRoute
  '/brindes/': typeof BrindesIndexRoute
  '/fita-de-cetim/': typeof FitaDeCetimIndexRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/bopp': typeof BoppRoute
  '/catalogo': typeof CatalogoRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contato': typeof ContatoRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/ferramentas': typeof FerramentasRoute
  '/marketplaces': typeof MarketplacesRoute
  '/ribbon': typeof RibbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brindes/agenda-personalizada': typeof BrindesAgendaPersonalizadaRoute
  '/etiquetas/preco': typeof EtiquetasPrecoRoute
  '/fita-de-cetim/impressora-para-cetim': typeof FitaDeCetimImpressoraParaCetimRoute
  '/brindes': typeof BrindesIndexRoute
  '/fita-de-cetim': typeof FitaDeCetimIndexRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/bopp': typeof BoppRoute
  '/brindes': typeof BrindesRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contato': typeof ContatoRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/ferramentas': typeof FerramentasRoute
  '/fita-de-cetim': typeof FitaDeCetimRouteWithChildren
  '/marketplaces': typeof MarketplacesRoute
  '/ribbon': typeof RibbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/brindes/agenda-personalizada': typeof BrindesAgendaPersonalizadaRoute
  '/etiquetas/preco': typeof EtiquetasPrecoRoute
  '/fita-de-cetim/impressora-para-cetim': typeof FitaDeCetimImpressoraParaCetimRoute
  '/brindes/': typeof BrindesIndexRoute
  '/fita-de-cetim/': typeof FitaDeCetimIndexRoute
  '/_authenticated/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/b2b'
    | '/blog'
    | '/bopp'
    | '/brindes'
    | '/catalogo'
    | '/conhecimento'
    | '/contato'
    | '/downloads'
    | '/empresa'
    | '/ferramentas'
    | '/fita-de-cetim'
    | '/marketplaces'
    | '/ribbon'
    | '/sitemap.xml'
    | '/admin'
    | '/brindes/agenda-personalizada'
    | '/etiquetas/preco'
    | '/fita-de-cetim/impressora-para-cetim'
    | '/brindes/'
    | '/fita-de-cetim/'
    | '/admin/importacao'
    | '/admin/produtos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/b2b'
    | '/blog'
    | '/bopp'
    | '/catalogo'
    | '/conhecimento'
    | '/contato'
    | '/downloads'
    | '/empresa'
    | '/ferramentas'
    | '/marketplaces'
    | '/ribbon'
    | '/sitemap.xml'
    | '/brindes/agenda-personalizada'
    | '/etiquetas/preco'
    | '/fita-de-cetim/impressora-para-cetim'
    | '/brindes'
    | '/fita-de-cetim'
    | '/admin/importacao'
    | '/admin/produtos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/auth'
    | '/b2b'
    | '/blog'
    | '/bopp'
    | '/brindes'
    | '/catalogo'
    | '/conhecimento'
    | '/contato'
    | '/downloads'
    | '/empresa'
    | '/ferramentas'
    | '/fita-de-cetim'
    | '/marketplaces'
    | '/ribbon'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/brindes/agenda-personalizada'
    | '/etiquetas/preco'
    | '/fita-de-cetim/impressora-para-cetim'
    | '/brindes/'
    | '/fita-de-cetim/'
    | '/_authenticated/admin/importacao'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  BlogRoute: typeof BlogRoute
  BoppRoute: typeof BoppRoute
  BrindesRoute: typeof BrindesRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  ContatoRoute: typeof ContatoRoute
  DownloadsRoute: typeof DownloadsRoute
  EmpresaRoute: typeof EmpresaRoute
  FerramentasRoute: typeof FerramentasRoute
  FitaDeCetimRoute: typeof FitaDeCetimRouteWithChildren
  MarketplacesRoute: typeof MarketplacesRoute
  RibbonRoute: typeof RibbonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EtiquetasPrecoRoute: typeof EtiquetasPrecoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ribbon': {
      id: '/ribbon'
      path: '/ribbon'
      fullPath: '/ribbon'
      preLoaderRoute: typeof RibbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplaces': {
      id: '/marketplaces'
      path: '/marketplaces'
      fullPath: '/marketplaces'
      preLoaderRoute: typeof MarketplacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fita-de-cetim': {
      id: '/fita-de-cetim'
      path: '/fita-de-cetim'
      fullPath: '/fita-de-cetim'
      preLoaderRoute: typeof FitaDeCetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brindes': {
      id: '/brindes'
      path: '/brindes'
      fullPath: '/brindes'
      preLoaderRoute: typeof BrindesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bopp': {
      id: '/bopp'
      path: '/bopp'
      fullPath: '/bopp'
      preLoaderRoute: typeof BoppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fita-de-cetim/': {
      id: '/fita-de-cetim/'
      path: '/'
      fullPath: '/fita-de-cetim/'
      preLoaderRoute: typeof FitaDeCetimIndexRouteImport
      parentRoute: typeof FitaDeCetimRoute
    }
    '/brindes/': {
      id: '/brindes/'
      path: '/'
      fullPath: '/brindes/'
      preLoaderRoute: typeof BrindesIndexRouteImport
      parentRoute: typeof BrindesRoute
    }
    '/fita-de-cetim/impressora-para-cetim': {
      id: '/fita-de-cetim/impressora-para-cetim'
      path: '/impressora-para-cetim'
      fullPath: '/fita-de-cetim/impressora-para-cetim'
      preLoaderRoute: typeof FitaDeCetimImpressoraParaCetimRouteImport
      parentRoute: typeof FitaDeCetimRoute
    }
    '/etiquetas/preco': {
      id: '/etiquetas/preco'
      path: '/etiquetas/preco'
      fullPath: '/etiquetas/preco'
      preLoaderRoute: typeof EtiquetasPrecoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brindes/agenda-personalizada': {
      id: '/brindes/agenda-personalizada'
      path: '/agenda-personalizada'
      fullPath: '/brindes/agenda-personalizada'
      preLoaderRoute: typeof BrindesAgendaPersonalizadaRouteImport
      parentRoute: typeof BrindesRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/importacao': {
      id: '/_authenticated/admin/importacao'
      path: '/importacao'
      fullPath: '/admin/importacao'
      preLoaderRoute: typeof AuthenticatedAdminImportacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminImportacaoRoute: typeof AuthenticatedAdminImportacaoRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminImportacaoRoute: AuthenticatedAdminImportacaoRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BrindesRouteChildren {
  BrindesAgendaPersonalizadaRoute: typeof BrindesAgendaPersonalizadaRoute
  BrindesIndexRoute: typeof BrindesIndexRoute
}

const BrindesRouteChildren: BrindesRouteChildren = {
  BrindesAgendaPersonalizadaRoute: BrindesAgendaPersonalizadaRoute,
  BrindesIndexRoute: BrindesIndexRoute,
}

const BrindesRouteWithChildren =
  BrindesRoute._addFileChildren(BrindesRouteChildren)

interface FitaDeCetimRouteChildren {
  FitaDeCetimImpressoraParaCetimRoute: typeof FitaDeCetimImpressoraParaCetimRoute
  FitaDeCetimIndexRoute: typeof FitaDeCetimIndexRoute
}

const FitaDeCetimRouteChildren: FitaDeCetimRouteChildren = {
  FitaDeCetimImpressoraParaCetimRoute: FitaDeCetimImpressoraParaCetimRoute,
  FitaDeCetimIndexRoute: FitaDeCetimIndexRoute,
}

const FitaDeCetimRouteWithChildren = FitaDeCetimRoute._addFileChildren(
  FitaDeCetimRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  BlogRoute: BlogRoute,
  BoppRoute: BoppRoute,
  BrindesRoute: BrindesRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  ContatoRoute: ContatoRoute,
  DownloadsRoute: DownloadsRoute,
  EmpresaRoute: EmpresaRoute,
  FerramentasRoute: FerramentasRoute,
  FitaDeCetimRoute: FitaDeCetimRouteWithChildren,
  MarketplacesRoute: MarketplacesRoute,
  RibbonRoute: RibbonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EtiquetasPrecoRoute: EtiquetasPrecoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
