/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RibbonRouteImport } from './routes/ribbon'
import { Route as MarketplacesRouteImport } from './routes/marketplaces'
import { Route as FitaDeCetimRouteImport } from './routes/fita-de-cetim'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConhecimentoRouteImport } from './routes/conhecimento'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BrindesRouteImport } from './routes/brindes'
import { Route as BoppRouteImport } from './routes/bopp'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FitaDeCetimIndexRouteImport } from './routes/fita-de-cetim.index'
import { Route as BrindesIndexRouteImport } from './routes/brindes.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PagamentoRecusadoRouteImport } from './routes/pagamento.recusado'
import { Route as PagamentoPendenteRouteImport } from './routes/pagamento.pendente'
import { Route as PagamentoAprovadoRouteImport } from './routes/pagamento.aprovado'
import { Route as FitaDeCetimImpressoraParaCetimRouteImport } from './routes/fita-de-cetim.impressora-para-cetim'
import { Route as EtiquetasPrecoRouteImport } from './routes/etiquetas.preco'
import { Route as BrindesAgendaPersonalizadaRouteImport } from './routes/brindes.agenda-personalizada'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated.minha-conta'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated.checkout'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedCheckoutIndexRouteImport } from './routes/_authenticated.checkout.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedPedidoIdRouteImport } from './routes/_authenticated.pedido.$id'
import { Route as AuthenticatedCheckoutRevisaoRouteImport } from './routes/_authenticated.checkout.revisao'
import { Route as AuthenticatedCheckoutPagamentoRouteImport } from './routes/_authenticated.checkout.pagamento'
import { Route as AuthenticatedCheckoutFreteRouteImport } from './routes/_authenticated.checkout.frete'
import { Route as AuthenticatedCheckoutEnderecoRouteImport } from './routes/_authenticated.checkout.endereco'
import { Route as AuthenticatedAdminImportacaoRouteImport } from './routes/_authenticated.admin.importacao'
import { Route as AuthenticatedAdminEnriquecimentoRouteImport } from './routes/_authenticated.admin.enriquecimento'
import { Route as AuthenticatedAdminProdutosIndexRouteImport } from './routes/_authenticated.admin.produtos.index'
import { Route as AuthenticatedAdminPedidosIndexRouteImport } from './routes/_authenticated.admin.pedidos.index'
import { Route as ApiPublicWebhooksMercadopagoRouteImport } from './routes/api/public/webhooks/mercadopago'
import { Route as AuthenticatedAdminProdutosIdRouteImport } from './routes/_authenticated.admin.produtos.$id'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated.admin.pedidos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RibbonRoute = RibbonRouteImport.update({
  id: '/ribbon',
  path: '/ribbon',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacesRoute = MarketplacesRouteImport.update({
  id: '/marketplaces',
  path: '/marketplaces',
  getParentRoute: () => rootRouteImport,
} as any)
const FitaDeCetimRoute = FitaDeCetimRouteImport.update({
  id: '/fita-de-cetim',
  path: '/fita-de-cetim',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecimentoRoute = ConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BrindesRoute = BrindesRouteImport.update({
  id: '/brindes',
  path: '/brindes',
  getParentRoute: () => rootRouteImport,
} as any)
const BoppRoute = BoppRouteImport.update({
  id: '/bopp',
  path: '/bopp',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FitaDeCetimIndexRoute = FitaDeCetimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FitaDeCetimRoute,
} as any)
const BrindesIndexRoute = BrindesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrindesRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRecusadoRoute = PagamentoRecusadoRouteImport.update({
  id: '/pagamento/recusado',
  path: '/pagamento/recusado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoPendenteRoute = PagamentoPendenteRouteImport.update({
  id: '/pagamento/pendente',
  path: '/pagamento/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoAprovadoRoute = PagamentoAprovadoRouteImport.update({
  id: '/pagamento/aprovado',
  path: '/pagamento/aprovado',
  getParentRoute: () => rootRouteImport,
} as any)
const FitaDeCetimImpressoraParaCetimRoute =
  FitaDeCetimImpressoraParaCetimRouteImport.update({
    id: '/impressora-para-cetim',
    path: '/impressora-para-cetim',
    getParentRoute: () => FitaDeCetimRoute,
  } as any)
const EtiquetasPrecoRoute = EtiquetasPrecoRouteImport.update({
  id: '/etiquetas/preco',
  path: '/etiquetas/preco',
  getParentRoute: () => rootRouteImport,
} as any)
const BrindesAgendaPersonalizadaRoute =
  BrindesAgendaPersonalizadaRouteImport.update({
    id: '/agenda-personalizada',
    path: '/agenda-personalizada',
    getParentRoute: () => BrindesRoute,
  } as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutIndexRoute =
  AuthenticatedCheckoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPedidoIdRoute = AuthenticatedPedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRevisaoRoute =
  AuthenticatedCheckoutRevisaoRouteImport.update({
    id: '/revisao',
    path: '/revisao',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedCheckoutPagamentoRoute =
  AuthenticatedCheckoutPagamentoRouteImport.update({
    id: '/pagamento',
    path: '/pagamento',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedCheckoutFreteRoute =
  AuthenticatedCheckoutFreteRouteImport.update({
    id: '/frete',
    path: '/frete',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedCheckoutEnderecoRoute =
  AuthenticatedCheckoutEnderecoRouteImport.update({
    id: '/endereco',
    path: '/endereco',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedAdminImportacaoRoute =
  AuthenticatedAdminImportacaoRouteImport.update({
    id: '/importacao',
    path: '/importacao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnriquecimentoRoute =
  AuthenticatedAdminEnriquecimentoRouteImport.update({
    id: '/enriquecimento',
    path: '/enriquecimento',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProdutosIndexRoute =
  AuthenticatedAdminProdutosIndexRouteImport.update({
    id: '/produtos/',
    path: '/produtos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosIndexRoute =
  AuthenticatedAdminPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicWebhooksMercadopagoRoute =
  ApiPublicWebhooksMercadopagoRouteImport.update({
    id: '/api/public/webhooks/mercadopago',
    path: '/api/public/webhooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminProdutosIdRoute =
  AuthenticatedAdminProdutosIdRouteImport.update({
    id: '/produtos/$id',
    path: '/produtos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/pedidos/$id',
    path: '/pedidos/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/bopp': typeof BoppRoute
  '/brindes': typeof BrindesRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contato': typeof ContatoRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/ferramentas': typeof FerramentasRoute
  '/fita-de-cetim': typeof FitaDeCetimRouteWithChildren
  '/marketplaces': typeof MarketplacesRoute
  '/ribbon': typeof RibbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/brindes/agenda-personalizada': typeof BrindesAgendaPersonalizadaRoute
  '/etiquetas/preco': typeof EtiquetasPrecoRoute
  '/fita-de-cetim/impressora-para-cetim': typeof FitaDeCetimImpressoraParaCetimRoute
  '/pagamento/aprovado': typeof PagamentoAprovadoRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/brindes/': typeof BrindesIndexRoute
  '/fita-de-cetim/': typeof FitaDeCetimIndexRoute
  '/admin/enriquecimento': typeof AuthenticatedAdminEnriquecimentoRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/checkout/endereco': typeof AuthenticatedCheckoutEnderecoRoute
  '/checkout/frete': typeof AuthenticatedCheckoutFreteRoute
  '/checkout/pagamento': typeof AuthenticatedCheckoutPagamentoRoute
  '/checkout/revisao': typeof AuthenticatedCheckoutRevisaoRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/admin/pedidos/': typeof AuthenticatedAdminPedidosIndexRoute
  '/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/bopp': typeof BoppRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contato': typeof ContatoRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/ferramentas': typeof FerramentasRoute
  '/marketplaces': typeof MarketplacesRoute
  '/ribbon': typeof RibbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/brindes/agenda-personalizada': typeof BrindesAgendaPersonalizadaRoute
  '/etiquetas/preco': typeof EtiquetasPrecoRoute
  '/fita-de-cetim/impressora-para-cetim': typeof FitaDeCetimImpressoraParaCetimRoute
  '/pagamento/aprovado': typeof PagamentoAprovadoRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/brindes': typeof BrindesIndexRoute
  '/fita-de-cetim': typeof FitaDeCetimIndexRoute
  '/admin/enriquecimento': typeof AuthenticatedAdminEnriquecimentoRoute
  '/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/checkout/endereco': typeof AuthenticatedCheckoutEnderecoRoute
  '/checkout/frete': typeof AuthenticatedCheckoutFreteRoute
  '/checkout/pagamento': typeof AuthenticatedCheckoutPagamentoRoute
  '/checkout/revisao': typeof AuthenticatedCheckoutRevisaoRoute
  '/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/checkout': typeof AuthenticatedCheckoutIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosIndexRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/b2b': typeof B2bRoute
  '/blog': typeof BlogRoute
  '/bopp': typeof BoppRoute
  '/brindes': typeof BrindesRouteWithChildren
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/conhecimento': typeof ConhecimentoRoute
  '/contato': typeof ContatoRoute
  '/downloads': typeof DownloadsRoute
  '/empresa': typeof EmpresaRoute
  '/ferramentas': typeof FerramentasRoute
  '/fita-de-cetim': typeof FitaDeCetimRouteWithChildren
  '/marketplaces': typeof MarketplacesRoute
  '/ribbon': typeof RibbonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/brindes/agenda-personalizada': typeof BrindesAgendaPersonalizadaRoute
  '/etiquetas/preco': typeof EtiquetasPrecoRoute
  '/fita-de-cetim/impressora-para-cetim': typeof FitaDeCetimImpressoraParaCetimRoute
  '/pagamento/aprovado': typeof PagamentoAprovadoRoute
  '/pagamento/pendente': typeof PagamentoPendenteRoute
  '/pagamento/recusado': typeof PagamentoRecusadoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/brindes/': typeof BrindesIndexRoute
  '/fita-de-cetim/': typeof FitaDeCetimIndexRoute
  '/_authenticated/admin/enriquecimento': typeof AuthenticatedAdminEnriquecimentoRoute
  '/_authenticated/admin/importacao': typeof AuthenticatedAdminImportacaoRoute
  '/_authenticated/checkout/endereco': typeof AuthenticatedCheckoutEnderecoRoute
  '/_authenticated/checkout/frete': typeof AuthenticatedCheckoutFreteRoute
  '/_authenticated/checkout/pagamento': typeof AuthenticatedCheckoutPagamentoRoute
  '/_authenticated/checkout/revisao': typeof AuthenticatedCheckoutRevisaoRoute
  '/_authenticated/pedido/$id': typeof AuthenticatedPedidoIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/_authenticated/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
  '/api/public/webhooks/mercadopago': typeof ApiPublicWebhooksMercadopagoRoute
  '/_authenticated/admin/pedidos/': typeof AuthenticatedAdminPedidosIndexRoute
  '/_authenticated/admin/produtos/': typeof AuthenticatedAdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/avaliacoes'
    | '/b2b'
    | '/blog'
    | '/bopp'
    | '/brindes'
    | '/carrinho'
    | '/catalogo'
    | '/conhecimento'
    | '/contato'
    | '/downloads'
    | '/empresa'
    | '/ferramentas'
    | '/fita-de-cetim'
    | '/marketplaces'
    | '/ribbon'
    | '/sitemap.xml'
    | '/admin'
    | '/checkout'
    | '/minha-conta'
    | '/brindes/agenda-personalizada'
    | '/etiquetas/preco'
    | '/fita-de-cetim/impressora-para-cetim'
    | '/pagamento/aprovado'
    | '/pagamento/pendente'
    | '/pagamento/recusado'
    | '/produto/$slug'
    | '/brindes/'
    | '/fita-de-cetim/'
    | '/admin/enriquecimento'
    | '/admin/importacao'
    | '/checkout/endereco'
    | '/checkout/frete'
    | '/checkout/pagamento'
    | '/checkout/revisao'
    | '/pedido/$id'
    | '/admin/'
    | '/checkout/'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/api/public/webhooks/mercadopago'
    | '/admin/pedidos/'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/avaliacoes'
    | '/b2b'
    | '/blog'
    | '/bopp'
    | '/carrinho'
    | '/catalogo'
    | '/conhecimento'
    | '/contato'
    | '/downloads'
    | '/empresa'
    | '/ferramentas'
    | '/marketplaces'
    | '/ribbon'
    | '/sitemap.xml'
    | '/minha-conta'
    | '/brindes/agenda-personalizada'
    | '/etiquetas/preco'
    | '/fita-de-cetim/impressora-para-cetim'
    | '/pagamento/aprovado'
    | '/pagamento/pendente'
    | '/pagamento/recusado'
    | '/produto/$slug'
    | '/brindes'
    | '/fita-de-cetim'
    | '/admin/enriquecimento'
    | '/admin/importacao'
    | '/checkout/endereco'
    | '/checkout/frete'
    | '/checkout/pagamento'
    | '/checkout/revisao'
    | '/pedido/$id'
    | '/admin'
    | '/checkout'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
    | '/api/public/webhooks/mercadopago'
    | '/admin/pedidos'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/auth'
    | '/avaliacoes'
    | '/b2b'
    | '/blog'
    | '/bopp'
    | '/brindes'
    | '/carrinho'
    | '/catalogo'
    | '/conhecimento'
    | '/contato'
    | '/downloads'
    | '/empresa'
    | '/ferramentas'
    | '/fita-de-cetim'
    | '/marketplaces'
    | '/ribbon'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/checkout'
    | '/_authenticated/minha-conta'
    | '/brindes/agenda-personalizada'
    | '/etiquetas/preco'
    | '/fita-de-cetim/impressora-para-cetim'
    | '/pagamento/aprovado'
    | '/pagamento/pendente'
    | '/pagamento/recusado'
    | '/produto/$slug'
    | '/brindes/'
    | '/fita-de-cetim/'
    | '/_authenticated/admin/enriquecimento'
    | '/_authenticated/admin/importacao'
    | '/_authenticated/checkout/endereco'
    | '/_authenticated/checkout/frete'
    | '/_authenticated/checkout/pagamento'
    | '/_authenticated/checkout/revisao'
    | '/_authenticated/pedido/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/checkout/'
    | '/_authenticated/admin/pedidos/$id'
    | '/_authenticated/admin/produtos/$id'
    | '/api/public/webhooks/mercadopago'
    | '/_authenticated/admin/pedidos/'
    | '/_authenticated/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  B2bRoute: typeof B2bRoute
  BlogRoute: typeof BlogRoute
  BoppRoute: typeof BoppRoute
  BrindesRoute: typeof BrindesRouteWithChildren
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  ConhecimentoRoute: typeof ConhecimentoRoute
  ContatoRoute: typeof ContatoRoute
  DownloadsRoute: typeof DownloadsRoute
  EmpresaRoute: typeof EmpresaRoute
  FerramentasRoute: typeof FerramentasRoute
  FitaDeCetimRoute: typeof FitaDeCetimRouteWithChildren
  MarketplacesRoute: typeof MarketplacesRoute
  RibbonRoute: typeof RibbonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EtiquetasPrecoRoute: typeof EtiquetasPrecoRoute
  PagamentoAprovadoRoute: typeof PagamentoAprovadoRoute
  PagamentoPendenteRoute: typeof PagamentoPendenteRoute
  PagamentoRecusadoRoute: typeof PagamentoRecusadoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicWebhooksMercadopagoRoute: typeof ApiPublicWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ribbon': {
      id: '/ribbon'
      path: '/ribbon'
      fullPath: '/ribbon'
      preLoaderRoute: typeof RibbonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplaces': {
      id: '/marketplaces'
      path: '/marketplaces'
      fullPath: '/marketplaces'
      preLoaderRoute: typeof MarketplacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fita-de-cetim': {
      id: '/fita-de-cetim'
      path: '/fita-de-cetim'
      fullPath: '/fita-de-cetim'
      preLoaderRoute: typeof FitaDeCetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecimento': {
      id: '/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof ConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brindes': {
      id: '/brindes'
      path: '/brindes'
      fullPath: '/brindes'
      preLoaderRoute: typeof BrindesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bopp': {
      id: '/bopp'
      path: '/bopp'
      fullPath: '/bopp'
      preLoaderRoute: typeof BoppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fita-de-cetim/': {
      id: '/fita-de-cetim/'
      path: '/'
      fullPath: '/fita-de-cetim/'
      preLoaderRoute: typeof FitaDeCetimIndexRouteImport
      parentRoute: typeof FitaDeCetimRoute
    }
    '/brindes/': {
      id: '/brindes/'
      path: '/'
      fullPath: '/brindes/'
      preLoaderRoute: typeof BrindesIndexRouteImport
      parentRoute: typeof BrindesRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/recusado': {
      id: '/pagamento/recusado'
      path: '/pagamento/recusado'
      fullPath: '/pagamento/recusado'
      preLoaderRoute: typeof PagamentoRecusadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/pendente': {
      id: '/pagamento/pendente'
      path: '/pagamento/pendente'
      fullPath: '/pagamento/pendente'
      preLoaderRoute: typeof PagamentoPendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/aprovado': {
      id: '/pagamento/aprovado'
      path: '/pagamento/aprovado'
      fullPath: '/pagamento/aprovado'
      preLoaderRoute: typeof PagamentoAprovadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fita-de-cetim/impressora-para-cetim': {
      id: '/fita-de-cetim/impressora-para-cetim'
      path: '/impressora-para-cetim'
      fullPath: '/fita-de-cetim/impressora-para-cetim'
      preLoaderRoute: typeof FitaDeCetimImpressoraParaCetimRouteImport
      parentRoute: typeof FitaDeCetimRoute
    }
    '/etiquetas/preco': {
      id: '/etiquetas/preco'
      path: '/etiquetas/preco'
      fullPath: '/etiquetas/preco'
      preLoaderRoute: typeof EtiquetasPrecoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brindes/agenda-personalizada': {
      id: '/brindes/agenda-personalizada'
      path: '/agenda-personalizada'
      fullPath: '/brindes/agenda-personalizada'
      preLoaderRoute: typeof BrindesAgendaPersonalizadaRouteImport
      parentRoute: typeof BrindesRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/': {
      id: '/_authenticated/checkout/'
      path: '/'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AuthenticatedCheckoutIndexRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/pedido/$id': {
      id: '/_authenticated/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof AuthenticatedPedidoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/revisao': {
      id: '/_authenticated/checkout/revisao'
      path: '/revisao'
      fullPath: '/checkout/revisao'
      preLoaderRoute: typeof AuthenticatedCheckoutRevisaoRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/checkout/pagamento': {
      id: '/_authenticated/checkout/pagamento'
      path: '/pagamento'
      fullPath: '/checkout/pagamento'
      preLoaderRoute: typeof AuthenticatedCheckoutPagamentoRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/checkout/frete': {
      id: '/_authenticated/checkout/frete'
      path: '/frete'
      fullPath: '/checkout/frete'
      preLoaderRoute: typeof AuthenticatedCheckoutFreteRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/checkout/endereco': {
      id: '/_authenticated/checkout/endereco'
      path: '/endereco'
      fullPath: '/checkout/endereco'
      preLoaderRoute: typeof AuthenticatedCheckoutEnderecoRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/admin/importacao': {
      id: '/_authenticated/admin/importacao'
      path: '/importacao'
      fullPath: '/admin/importacao'
      preLoaderRoute: typeof AuthenticatedAdminImportacaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enriquecimento': {
      id: '/_authenticated/admin/enriquecimento'
      path: '/enriquecimento'
      fullPath: '/admin/enriquecimento'
      preLoaderRoute: typeof AuthenticatedAdminEnriquecimentoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produtos/': {
      id: '/_authenticated/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos/': {
      id: '/_authenticated/admin/pedidos/'
      path: '/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/mercadopago': {
      id: '/api/public/webhooks/mercadopago'
      path: '/api/public/webhooks/mercadopago'
      fullPath: '/api/public/webhooks/mercadopago'
      preLoaderRoute: typeof ApiPublicWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/produtos/$id': {
      id: '/_authenticated/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnriquecimentoRoute: typeof AuthenticatedAdminEnriquecimentoRoute
  AuthenticatedAdminImportacaoRoute: typeof AuthenticatedAdminImportacaoRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
  AuthenticatedAdminProdutosIdRoute: typeof AuthenticatedAdminProdutosIdRoute
  AuthenticatedAdminPedidosIndexRoute: typeof AuthenticatedAdminPedidosIndexRoute
  AuthenticatedAdminProdutosIndexRoute: typeof AuthenticatedAdminProdutosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnriquecimentoRoute: AuthenticatedAdminEnriquecimentoRoute,
  AuthenticatedAdminImportacaoRoute: AuthenticatedAdminImportacaoRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  AuthenticatedAdminProdutosIdRoute: AuthenticatedAdminProdutosIdRoute,
  AuthenticatedAdminPedidosIndexRoute: AuthenticatedAdminPedidosIndexRoute,
  AuthenticatedAdminProdutosIndexRoute: AuthenticatedAdminProdutosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCheckoutRouteChildren {
  AuthenticatedCheckoutEnderecoRoute: typeof AuthenticatedCheckoutEnderecoRoute
  AuthenticatedCheckoutFreteRoute: typeof AuthenticatedCheckoutFreteRoute
  AuthenticatedCheckoutPagamentoRoute: typeof AuthenticatedCheckoutPagamentoRoute
  AuthenticatedCheckoutRevisaoRoute: typeof AuthenticatedCheckoutRevisaoRoute
  AuthenticatedCheckoutIndexRoute: typeof AuthenticatedCheckoutIndexRoute
}

const AuthenticatedCheckoutRouteChildren: AuthenticatedCheckoutRouteChildren = {
  AuthenticatedCheckoutEnderecoRoute: AuthenticatedCheckoutEnderecoRoute,
  AuthenticatedCheckoutFreteRoute: AuthenticatedCheckoutFreteRoute,
  AuthenticatedCheckoutPagamentoRoute: AuthenticatedCheckoutPagamentoRoute,
  AuthenticatedCheckoutRevisaoRoute: AuthenticatedCheckoutRevisaoRoute,
  AuthenticatedCheckoutIndexRoute: AuthenticatedCheckoutIndexRoute,
}

const AuthenticatedCheckoutRouteWithChildren =
  AuthenticatedCheckoutRoute._addFileChildren(
    AuthenticatedCheckoutRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRouteWithChildren
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedPedidoIdRoute: typeof AuthenticatedPedidoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRouteWithChildren,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedPedidoIdRoute: AuthenticatedPedidoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BrindesRouteChildren {
  BrindesAgendaPersonalizadaRoute: typeof BrindesAgendaPersonalizadaRoute
  BrindesIndexRoute: typeof BrindesIndexRoute
}

const BrindesRouteChildren: BrindesRouteChildren = {
  BrindesAgendaPersonalizadaRoute: BrindesAgendaPersonalizadaRoute,
  BrindesIndexRoute: BrindesIndexRoute,
}

const BrindesRouteWithChildren =
  BrindesRoute._addFileChildren(BrindesRouteChildren)

interface FitaDeCetimRouteChildren {
  FitaDeCetimImpressoraParaCetimRoute: typeof FitaDeCetimImpressoraParaCetimRoute
  FitaDeCetimIndexRoute: typeof FitaDeCetimIndexRoute
}

const FitaDeCetimRouteChildren: FitaDeCetimRouteChildren = {
  FitaDeCetimImpressoraParaCetimRoute: FitaDeCetimImpressoraParaCetimRoute,
  FitaDeCetimIndexRoute: FitaDeCetimIndexRoute,
}

const FitaDeCetimRouteWithChildren = FitaDeCetimRoute._addFileChildren(
  FitaDeCetimRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  B2bRoute: B2bRoute,
  BlogRoute: BlogRoute,
  BoppRoute: BoppRoute,
  BrindesRoute: BrindesRouteWithChildren,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  ConhecimentoRoute: ConhecimentoRoute,
  ContatoRoute: ContatoRoute,
  DownloadsRoute: DownloadsRoute,
  EmpresaRoute: EmpresaRoute,
  FerramentasRoute: FerramentasRoute,
  FitaDeCetimRoute: FitaDeCetimRouteWithChildren,
  MarketplacesRoute: MarketplacesRoute,
  RibbonRoute: RibbonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EtiquetasPrecoRoute: EtiquetasPrecoRoute,
  PagamentoAprovadoRoute: PagamentoAprovadoRoute,
  PagamentoPendenteRoute: PagamentoPendenteRoute,
  PagamentoRecusadoRoute: PagamentoRecusadoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicWebhooksMercadopagoRoute: ApiPublicWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
